// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA26z_bH1iGVuZv95jU2iOvdhFxQWvsUAI',
    appId: '1:370551545828:web:be5008763226125425b1f1',
    messagingSenderId: '370551545828',
    projectId: 'chatit-b37ad',
    authDomain: 'chatit-b37ad.firebaseapp.com',
    storageBucket: 'chatit-b37ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7g_5qG6MAyT9yJOdrN8zZHymFlwgQCao',
    appId: '1:370551545828:android:40ec3afa85a1fb9025b1f1',
    messagingSenderId: '370551545828',
    projectId: 'chatit-b37ad',
    storageBucket: 'chatit-b37ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_QWcprxK_BFBxWVVUfcnK6ACNRtBD2GA',
    appId: '1:370551545828:ios:b7e8bd67440ca5f825b1f1',
    messagingSenderId: '370551545828',
    projectId: 'chatit-b37ad',
    storageBucket: 'chatit-b37ad.appspot.com',
    iosBundleId: 'com.example.chatIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_QWcprxK_BFBxWVVUfcnK6ACNRtBD2GA',
    appId: '1:370551545828:ios:b7e8bd67440ca5f825b1f1',
    messagingSenderId: '370551545828',
    projectId: 'chatit-b37ad',
    storageBucket: 'chatit-b37ad.appspot.com',
    iosBundleId: 'com.example.chatIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA26z_bH1iGVuZv95jU2iOvdhFxQWvsUAI',
    appId: '1:370551545828:web:2cf6ecff84712b5625b1f1',
    messagingSenderId: '370551545828',
    projectId: 'chatit-b37ad',
    authDomain: 'chatit-b37ad.firebaseapp.com',
    storageBucket: 'chatit-b37ad.appspot.com',
  );

}